### ISSUE TITLE
BUILD FAILED Compose Multiplatform project trying to run Desktop App.

### ISSUE THREAD

**Issue by BryanKAdams** [GitLiveApp/firebase-java-sdk#16]
Download https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-desktop/1.6.1/ui-util-desktop-1.6.1.pom, took 111 ms (2.26 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-desktop/1.6.1/ui-util-desktop-1.6.1.module, took 24 ms (3.21 kB)
Exception in thread "main" java.lang.NoSuchMethodError: 'void androidx.lifecycle.LifecycleRegistry.setCurrentState(androidx.lifecycle.Lifecycle$State)'
	at androidx.compose.ui.scene.ComposeContainer.updateLifecycleState(ComposeContainer.desktop.kt:436)
	at androidx.compose.ui.scene.ComposeContainer.onChangeWindowFocus(ComposeContainer.desktop.kt:216)
	at androidx.compose.ui.scene.ComposeContainer.setWindow(ComposeContainer.desktop.kt:297)
	at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:164)
	at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:82)
	at androidx.compose.ui.awt.ComposeWindowPanel.<init>(ComposeWindowPanel.desktop.kt:56)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:65)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:63)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:182)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:176)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:409)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:406)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:70)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:69)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:desktopRun'.
> Process 'command '/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

     desktopMain.dependencies {
            implementation(compose.desktop.currentOs)

            implementation(libs.firebase.java.sdk)

        }
        
         commonMain.dependencies {
       //firebase
            implementation(libs.gitlive.firebase.common)
            implementation(libs.gitlive.firebase.firestore)
}

**Comment by nbransby** [comment]
try with 0.4.3

**Comment by BryanKAdams** [comment]
@nbransby seems fixed, will this change get rolled into firebase-kotlin-sdk as well?
