### ISSUE TITLE
JVM crash on init

### ISSUE THREAD

**Issue by dmazgalin** [GitLiveApp/firebase-java-sdk#19]
Hi Folks, I was trying to make a multiplatform app. At the moment have some issues with Firebase init.

Have following code: 

        val options = FirebaseOptions(
            applicationId = "***",
            projectId = "***",
            apiKey = "***"
        )

        Firebase.initialize(Application(), options, "Sample")

after this line the app is showing in console following stack trace.

FirebaseApp Device unlocked: initializing all Firebase APIs for app Sample
kotlinx.serialization.json.internal.JsonDecodingException: Cannot read Json element because of unexpected end of the input at path: $
JSON input: 
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.JsonTreeReader.read(JsonTreeReader.kt:107)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeJsonElement(StreamingJsonDecoder.kt:50)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:50)
	at kotlinx.serialization.json.JsonElementSerializer.deserialize(JsonElementSerializers.kt:27)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:136)
	at com.google.firebase.auth.FirebaseAuth.<init>(FirebaseAuth.kt:153)
	at com.google.firebase.auth.FirebaseAuthRegistrar.lambda$getComponents$0(FirebaseAuthRegistrar.java:21)
	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
	at dev.gitlive.firebase.FirebaseKt.initialize(firebase.kt:27)
	at com.sample.ComposableSingletons$ApplicationKt$lambda-3$1.invoke(Application.kt:67)

**Comment by nbransby** [comment]
installations not available in the java sdk as no one has attempted to port it yet
